name: Issue
description: Meld een probleem
body:
  - type: textarea
    id: probleem
    attributes:
      label: Probleem
      description: Beschrijf het probleem.
    validations:
      required: true

  - type: textarea
    id: screenshot
    attributes:
      label: Screenshot
      description: Sleep een screenshot hierheen of plak hem hier.
